FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    docker.io \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

CMD ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]